#!/usr/bin/env bash

# bump_version - increase the app version and push to a new branch

set -o errexit
set -o pipefail
set -o xtrace

usage() {
    echo -e "bump_version - increase the app version"
    echo -e ""
    echo -e "Usage:"
    echo -e " $ bump_version <new_version>"
}

if [[ -z $1 ]]; then
    usage
    exit 1
fi

build_version="$1"
version="${build_version%.*}"

# Create a new git branch
git fetch upstream
git checkout -b bump-${build_version} --no-track upstream/master

# Update the version numbers in app.json
jq --arg bv "${build_version}" --arg v "${version}" '.expo.version |= $v | .expo.ios.buildNumber |= $bv' app.json > app.tmp.json && mv app.tmp.json app.json

# Run prebuild to update the version in ios/Jellyfin/Info.plist
npm run build -- --no-install

# Update package.json version
npm version "${version}"

# Commit and push the changes
git add app.json ios/Jellyfin/Info.plist package.json package-lock.json
git commit -m "Bump build number to ${build_version}"
git push -u origin bump-${build_version}
